name: Terraform Deployment

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.5

    - name: List files in environments/dev
      run: ls -la environments/dev

    - name: Terraform Init
      run: |
        cd environments/dev
        terraform init -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" -backend-config="access_key=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}" -backend-config="key=terraform.tfstate"

    - name: Terraform Validate
      run: |
        cd environments/dev
        terraform validate

    - name: Terraform Plan
      run: |
        cd environments/dev
        terraform plan -var-file=terraform.tfvars

    - name: Terraform Apply
      run: |
        cd environments/dev
        terraform apply -auto-approve -var-file=terraform.tfvars
